from __future__ import annotations

from pathlib import Path

import pandas as pd
import streamlit as st


RESULTS_DIR = Path("results")
SUMMARIES_DIR = RESULTS_DIR / "v3" / "summaries"
DEMOS_DIR = RESULTS_DIR / "v3" / "demos"


def get_latest_summary_file() -> Path | None:
    """Return the newest V3 evaluation summary CSV, if one exists."""
    if not SUMMARIES_DIR.exists():
        return None
    files = sorted(SUMMARIES_DIR.glob("*.csv"))
    if not files:
        return None
    return files[-1]


def get_demo_files() -> list[Path]:
    """Return available V3 demo episode CSV files."""
    if not DEMOS_DIR.exists():
        return []
    return sorted(DEMOS_DIR.glob("*.csv"))


def load_csv(path: Path) -> pd.DataFrame:
    """Load a dashboard CSV file into a DataFrame."""
    return pd.read_csv(path)


def main() -> None:
    """Render the Streamlit dashboard for V3 summaries and demo episodes."""
    st.set_page_config(page_title="SmartGrid-ES V3 Dashboard", layout="wide")

    st.title("SmartGrid-ES V3 Dashboard")
    st.write(
        "This dashboard shows the latest evaluation summary and the available demo episodes "
        "generated by the V3 training and evaluation scripts."
    )

    st.subheader("Evaluation summary")

    summary_file = get_latest_summary_file()
    if summary_file is None:
        st.warning("No V3 evaluation summary files were found in results/v3/summaries.")
    else:
        summary_df = load_csv(summary_file)
        st.caption(f"Loaded file: {summary_file.name}")
        st.dataframe(summary_df, use_container_width=True)

        if "scenario" in summary_df.columns and "avg_reward" in summary_df.columns:
            reward_chart = summary_df.set_index("scenario")["avg_reward"]
            st.bar_chart(reward_chart)

        metric_columns = [
            col
            for col in [
                "avg_reward",
                "avg_coverage",
                "avg_grid_bought",
                "avg_sold",
                "avg_wasted_renewable",
                "avg_risk_score",
                "invalid_action_rate",
            ]
            if col in summary_df.columns
        ]
        if metric_columns:
            if "scenario" in summary_df.columns:
                st.line_chart(summary_df.set_index("scenario")[metric_columns])
            else:
                st.line_chart(summary_df[metric_columns])

    st.divider()

    st.subheader("Demo episode viewer")

    demo_files = get_demo_files()
    if not demo_files:
        st.warning("No V3 demo episode CSV files were found in results/v3/demos.")
        return

    selected_demo_name = st.selectbox(
        "Select a demo episode file",
        options=[path.name for path in demo_files],
    )

    selected_demo_path = DEMOS_DIR / selected_demo_name
    demo_df = load_csv(selected_demo_path)

    st.caption(f"Loaded file: {selected_demo_path.name}")
    st.dataframe(demo_df, use_container_width=True)

    chart_columns = [
        col
        for col in ["battery", "demand", "renewable", "price_level", "reward", "risk_score"]
        if col in demo_df.columns
    ]
    if chart_columns:
        st.subheader("Episode evolution")
        st.line_chart(demo_df[chart_columns])

    if "action" in demo_df.columns:
        st.subheader("Actions taken")
        st.bar_chart(demo_df["action"].value_counts().sort_index())


if __name__ == "__main__":
    main()
